name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      consul:
        image: consul
        ports:
          - 8500:8500

    steps:

    - run: sleep 5

    - name: Checkout
      uses: actions/checkout@v2

    - name: CURL-ACTION1
      uses: enflo/curl-action@v1.2
      with:
        curl: http://localhost:8500
      continue-on-error: true

    - run: sleep 5


    - name: CURL-ACTION2
      uses: enflo/curl-action@v1.2
      with:
        curl: http://localhost:8500
      continue-on-error: true

    - run: sleep 5

    - name: CURL-ACTION3
      uses: enflo/curl-action@v1.2
      with:
        curl: http://localhost:8500
      continue-on-error: true

    - run: sleep 5

    - name: CURL-ACTION4
      uses: enflo/curl-action@v1.2
      with:
        curl: http://localhost:8500
      continue-on-error: true


    - run: sleep 5

    - name: CURL-ACTION5
      uses: enflo/curl-action@v1.2
      with:
        curl: http://localhost:8500
      continue-on-error: true


    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Pack
      run: dotnet pack --no-build --verbosity normal
